### ISSUE TITLE
Simplify the environment files

### ISSUE THREAD

**Issue by brian-rose** [mikemorris12/UTCDW_Guidebook#1]
I tried to follow guidance in section [1.1 Setting Up Your Python Environment](https://utcdw.physics.utoronto.ca/UTCDW_Guidebook/Chapter1/section1.1_python_env.html) on a Mac laptop. I think the instructions could be clarified.

First, the conda config commands like 
```
conda config --prepend channels conda-forge
```
are not needed if the user is installing via an environment file, since channels are set explicitly in the file.

I tried using the supplied `UTCDW_env_MacOS.yml` to set up an environment, but this failed. The supplied files seem to be raw output from `conda list` rather than minimal descriptors of dependencies. With all the extremely detailed version pins in these files, conda / mamba were unable to solve the environment on my machine.

I found I could easily adapt the explicit dependencies on [the same page](https://utcdw.physics.utoronto.ca/UTCDW_Guidebook/Chapter1/section1.1_python_env.html) into a working conda environment file like this:
```
name: UTCDW-env
channels:
  - conda-forge
  - defaults
  - claut
dependencies:
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - cartopy
  - nc-time-axis
  - pandas
  - jupyter
  - xarray
  - netCDF4
  - zarr
  - ec3
  - esgf-pyclient
  - gcsfs
  - siphon
  - requests
  - tqdm
  - dask
  - dask-ml
  - scikit-learn
  - xesmf
  - xclim
  - xskillscore
  - libpysal 
  - esda
```

With this homemade environment file, I was able to quickly create a working computational environment and run the notebooks. I suggest replacing the highly pinned comprehensive environment descriptor files in the repository with some simple like the above, so that users can get up and running quickly without detailed knowledge about package versions and dependencies.

**Comment by brian-rose** [comment]
Related to my review of the JOSE submission, https://github.com/openjournals/jose-reviews/issues/243

**Comment by mikemorris12** [comment]
I've incorporated the suggested change into the JOSE-Submission branch in commit [f8a9274](https://github.com/mikemorris12/UTCDW_Guidebook/commit/f8a92741c0974eaa3f597fa6e7a58864b80abe82). Thanks!
